db.runCommand({
    collMod:"validator",
    validator:{
        $jsonSchema:{
            required:['name','add'],
            properties:{
                name:{
                    bsonType:"number"
                }
            }
        }
    },
    validationAction:"error"
})